const skincareProducts = [
  {
    nama: "The Ordinary Glycolic Acid 7% Toning Solution",
    kategori: "serum/salep",
    jerawat: "Blackhead",
    jenisSkincare: "Serum/Salep",
    rekomendasi: "Redakan peradangan, kontrol sebum", // Mapped from 'Keterangan' as a general recommendation
    gambar: "images/produk/serum-g.png", // Original 'Gambar produk' value
    kandungan: "Glycolic acid",
    keterangan: "Redakan peradangan, kontrol sebum",
    link: "https://s.shopee.co.id/4fjxW4Yh0O",
  },
  {
    nama: "COSRX Low pH Good Morning Cleanser",
    kategori: "cleanser",
    jerawat: "Blackhead",
    jenisSkincare: "Cleanser",
    rekomendasi: "Membersihkan pori & mengangkat sel kulit mati",
    gambar: "images/produk/cleanser-e.jpg",
    kandungan: "Salicylic Acid",
    keterangan: "Membersihkan pori & mengangkat sel kulit mati",
    link: "https://s.shopee.co.id/1qPm0MyIqY",
  },
  {
    nama: "Some By Mi AHA BHA PHA Toner",
    kategori: "toner/moisturizer",
    jerawat: "Blackhead",
    jenisSkincare: "Toner/Moisturizer",
    rekomendasi: "Eksfoliasi ringan, mencegah pori-pori tersumbat",
    gambar: "images/produk/toner-g.jpg",
    kandungan: "AHA, BHA, PHA",
    keterangan: "Eksfoliasi ringan, mencegah pori-pori tersumbat",
    link: "https://s.shopee.co.id/4VQXBOgnLT",
  },
  {
    nama: "La Roche-Posay Effaclar Duo+",
    kategori: "serum/salep",
    jerawat: "Conglobata",
    jenisSkincare: "Serum/Salep",
    rekomendasi: "Krim Tropikal",
    gambar: "images/produk/serum-h.png",
    kandungan: "benzoyl peroxide dan niacinamide",
    keterangan: "Krim Tropikal",
    link: "https://s.shopee.co.id/40UGitn9IU",
  },
  {
    nama: "Avoskin Natural Sublime Facial Cleanser",
    kategori: "cleanser",
    jerawat: "Conglobata",
    jenisSkincare: "Cleanser",
    rekomendasi: "Menenangkan kulit iritasi berat",
    gambar: "images/produk/cleanser-g.png",
    kandungan: "Centella Asiatica, Glycerin",
    keterangan: "Menenangkan kulit iritasi berat",
    link: "https://s.shopee.co.id/9KVmwOQAnG",
  },
  {
    nama: "ElsheSkin Acne Refresh Toner",
    kategori: "toner/moisturizer",
    jerawat: "Conglobata",
    jenisSkincare: "Toner/Moisturizer",
    rekomendasi: "Redakan inflamasi, mencegah jerawat lanjutan",
    gambar: "images/produk/toner-h.jpg",
    kandungan: "Salicylic Acis, Niacinamide",
    keterangan: "Redakan inflamasi, mencegah jerawat lanjutan",
    link: "https://s.shopee.co.id/9f8dL933Dz",
  },
  {
    nama: "Hada Labo Tamagohada Mild Peeling Face Wash",
    kategori: "cleanser",
    jerawat: "Crystalline",
    jenisSkincare: "Cleanser",
    rekomendasi: "Pembersih wajah dengan mild exfoliating",
    gambar: "images/produk/cleanser-h.png",
    kandungan: "AHA dan BHA",
    keterangan: "Pembersih wajah dengan mild exfoliating",
    link: "https://s.shopee.co.id/1qPm8xgqge",
  },
  {
    nama: "Avoskin Your Skin Bae Toner",
    kategori: "toner/moisturizer",
    jerawat: "Crystalline",
    jenisSkincare: "Toner/Moisturizer",
    rekomendasi: "Eksfoliasi lembut untuk milia",
    gambar: "images/produk/toner-i.jpg",
    kandungan: "Mandelic Acid",
    keterangan: "Eksfoliasi lembut untuk milia",
    link: "https://s.shopee.co.id/40UGbDHWWV",
  },
  {
    nama: "The Ordinary Lactic Acid 10% + HA",
    kategori: "serum/salep",
    jerawat: "Crystalline",
    jenisSkincare: "Serum/Salep",
    rekomendasi: "Eksfoliasi halus dan mengangkat milia",
    gambar: "images/produk/serum-i.png",
    kandungan: "Lactic Acid",
    keterangan: "Eksfoliasi halus dan mengangkat milia",
    link: "https://s.shopee.co.id/8fG6Gp8Ufo",
  },
  {
    nama: "La Roche-Posay Effaclar Medicated Gel Acne Cleanser",
    kategori: "cleanser",
    jerawat: "Crystic",
    jenisSkincare: "Cleanser",
    rekomendasi: "Gel pembersih wajah anti-jerawat.",
    gambar: "images/produk/cleanser-i.png",
    kandungan: "salicylic acid 2%",
    keterangan: "Gel pembersih wajah anti-jerawat.",
    link: "https://s.shopee.co.id/4L777eQqsK",
  },
  {
    nama: "COSRX Centella Water Toner",
    kategori: "toner/moisturizer",
    jerawat: "Crystic",
    jenisSkincare: "Toner/Moisturizer",
    rekomendasi: "Menenangkan kulit",
    gambar: "images/produk/toner-j.jpg",
    kandungan: "Centella Asiatica",
    keterangan: "Menenangkan kulit",
    link: "https://s.shopee.co.id/60FL660nSK",
  },
  {
    nama: "Avoskin Miraculous Retinol Ampoule",
    kategori: "serum/salep",
    jerawat: "Crystic",
    jenisSkincare: "Serum/Salep",
    rekomendasi: "Percepat penyembuhan jerawat dalam",
    gambar: "images/produk/serum-j.jpg",
    kandungan: "Retinol, Peptide",
    keterangan: "Percepat penyembuhan jerawat dalam",
    link: "https://s.shopee.co.id/3Av9izunfB",
  },
  {
    nama: "Duofilm Salicylic Acid 17% Solution",
    kategori: "serum/salep",
    jerawat: "Flat_wart",
    jenisSkincare: "Serum/Salep",
    rekomendasi: "Obat topikal untuk mengelupas lapisan kulit luar pada kutil, kapalan, dan mata ikan.",
    gambar: "images/produk/serum-e.jpg",
    kandungan: "Salicylic Acid 17%, Lactic Acid, Collodion",
    keterangan: "Obat topikal untuk mengelupas lapisan kulit luar pada kutil, kapalan, dan mata ikan. Salicylic Acid bekerja sebagai keratolitik yang melarutkan sel kulit mati. Digunakan sebagai spot treatment, hindari kontak dengan kulit sehat.",
    link: "https://shopee.com.my/Duofilm-Solution-15ml-for-Treatment-of-Warts-Corns-Calluses-i.85014835.18574216001",
  },
  {
    nama: "CeraVe SA Cleanser",
    kategori: "cleanser",
    jerawat: "Flat_wart",
    jenisSkincare: "Cleanser",
    rekomendasi: "Membersihkan kulit dari sel kulit mati dan sebum berlebih tanpa mengiritasi atau merusak skin barrier.",
    gambar: "images/produk/cleanser-c.jpg",
    kandungan: "Salicylic Acid (BHA), Ceramides (1, 3, 6-II), Niacinamide, Hyaluronic Acid",
    keterangan: "Membersihkan kulit dari sel kulit mati dan sebum berlebih tanpa mengiritasi atau merusak skin barrier. Cocok untuk kulit kasar, berjerawat, atau komedoan, dan bisa digunakan setiap hari.",
    link: "https://shopee.co.id/Cerave-SA-Smoothing-Cleanser-236ml-i.30736001.26674969951",
  },
  {
    nama: "La Roche-Posay Cicaplast Baume B5",
    kategori: "toner/moisturizer",
    jerawat: "Flat_wart",
    jenisSkincare: "Toner/Moisturizer",
    rekomendasi: "Balm serbaguna yang membantu memperbaiki skin barrier, menenangkan iritasi, dan mempercepat penyembuhan luka kecil atau kulit sensitif.",
    gambar: "images/produk/toner-b.png",
    kandungan: "Panthenol (Vitamin B5), Madecassoside (ekstrak Centella Asiatica), Zinc + Manganese, Shea Butter",
    keterangan: "Balm serbaguna yang membantu memperbaiki skin barrier, menenangkan iritasi, dan mempercepat penyembuhan luka kecil atau kulit sensitif. Aman untuk bayi, anak, maupun orang dewasa.",
    link: "https://shopee.co.id/list/La%20Roche%20Posay/Cicaplast%20Baume%20B5",
  },
  {
    nama: "Dermatix Ultra Gel 5 g",
    kategori: "serum/salep",
    jerawat: "Keloid",
    jenisSkincare: "Serum/Salep",
    rekomendasi: "Gel silikon transparan untuk perawatan bekas luka",
    gambar: "images/produk/serum-k.jpg",
    kandungan: "CPX Technology dan Vitamin C Ester",
    keterangan: "Gel silikon transparan untuk perawatan bekas luka",
    link: "https://shopee.co.id/Dermatix-Ultra-Gel-5-g-i.574119945.21737659080?sp_atk=fe08d806-9544-4b81-819d-b83455eb5706&xptdk=fe08d806-9544-4b81-819d-b83455eb5706",
  },
  {
    nama: "The Originote Hyalucera Toner",
    kategori: "toner/moisturizer",
    jerawat: "Keloid",
    jenisSkincare: "Toner/Moisturizer",
    rekomendasi: "Melembapkan & memperkuat skin barrier",
    gambar: "images/produk/toner-g.jpg",
    kandungan: "Ceramide, HA",
    keterangan: "Melembapkan & memperkuat skin barrier",
    link: "https://s.shopee.co.id/60FL6HIQ8k",
  },
  {
    nama: "Hada Labo Gokujyun Cleanser",
    kategori: "cleanser",
    jerawat: "Keloid",
    jenisSkincare: "Cleanser",
    rekomendasi: "Mengempiskan keloid dan menyamarkan bekas luka",
    gambar: "images/produk/cleanser-j.png",
    kandungan: "Onion Extract, Allium Cepa",
    keterangan: "Mengempiskan keloid dan menyamarkan bekas luka",
    link: "https://s.shopee.co.id/8AJpgL3tGDM",
  },
  {
    nama: "CeraVe Hydrating Cream-to-Foam Cleanser",
    kategori: "cleanser",
    jerawat: "Milium",
    jenisSkincare: "Cleanser",
    rekomendasi: "Membersihkan secara menyeluruh tanpa merusak skin barrier, cocok untuk kulit kering–normal.",
    gambar: "images/produk/cleanser-b.png",
    kandungan: "Ceramides, Amino Acids, Hyaluronic Acid",
    keterangan: "Membersihkan secara menyeluruh tanpa merusak skin barrier, cocok untuk kulit kering–normal.",
    link: "https://shopee.co.id/CeraVe-Menjaga-kelembapan-Hydrating-Cleanser-236-ml-%EF%BF%BD-Gentle-Face-Wash-with-Ceramide-for-Normal-to-Dry-Skin-Pembersih-Wajah-Untuk-Kulit-Kering--i.1108744801.19986272587?sp_atk=2e200c4f-a9de-4a08-8921-0e77da295dad&xptdk=2e200c4f-a9de-4a08-8921-0e77da295dad",
  },
  {
    nama: "Hada Labo Gokujyun Premium Lotion",
    kategori: "toner/moisturizer",
    jerawat: "Milium",
    jenisSkincare: "Toner/Moisturizer",
    rekomendasi: "Menghidrasi kulit secara mendalam dan menjaga kelembapan tanpa rasa lengket.",
    gambar: "images/produk/toner-d.jpg",
    kandungan: "5 jenis Hyaluronic Acid",
    keterangan: "Menghidrasi kulit secara mendalam dan menjaga kelembapan tanpa rasa lengket.",
    link: "https://shopee.co.id/Hada-Labo-Gokujyun-Premium-Ultimate-Moisturizing-Lotion-100ml-i.10689.5660146605?sp_atk=2ea297a9-0689-4c2c-9b1f-c81b07638393&xptdk=2ea297a9-0689-4c2c-9b1f-c81b07638393",
  },
  {
    nama: "The Ordinary Granactive Retinoid 2% Emulsion",
    kategori: "serum/salep",
    jerawat: "Milium",
    jenisSkincare: "Serum/Salep",
    rekomendasi: "Mendorong regenerasi sel kulit dan mengurangi tanda-tanda penuaan serta jerawat dengan iritasi minimal.",
    gambar: "images/produk/serum-b.jpeg",
    kandungan: "Hydroxypinacolone Retinoate (retinoid stabil)",
    keterangan: "Mendorong regenerasi sel kulit dan mengurangi tanda-tanda penuaan serta jerawat dengan iritasi minimal.",
    link: "https://shopee.co.id/The-Ordinary-Granactive-Retinoid-2-Emulsion-Retinol-Facial-serum-Anti-aging-Fine-Lines-Skin-Care-30ml-i.1314670677.27525423421?sp_atk=29815843-c724-43c8-9bff-cf5046aee396&xptdk=29815843-c724-43c8-9bff-cf5046aee396",
  },
  {
    nama: "La Roche-Posay Effaclar Purifying Foaming Gel",
    kategori: "cleanser",
    jerawat: "Papular",
    jenisSkincare: "Cleanser",
    rekomendasi: "Membersihkan kulit dari minyak berlebih dan kotoran tanpa membuat kulit kering atau tertarik.",
    gambar: "images/produk/cleanser-a.jpg",
    kandungan: "Zinc PCA, Thermal Spring Water",
    keterangan: "Membersihkan kulit dari minyak berlebih dan kotoran tanpa membuat kulit kering atau tertarik.",
    link: "https://shopee.co.id/La-Roche-Posay-Mengurangi-Minyak-Berlebih-Effaclar-Foaming-Gel-M-Cleanser-200ml-Facial-Wash-Kulit-Jerawat-Berminyak-i.433144176.9051394067?sp_atk=489a40ac-2229-4dad-92ce-bbaaf0769996&xptdk=489a40ac-2229-4dad-92ce-bbaaf0769996",
  },
  {
    nama: "COSRX Balancium Comfort Ceramide Cream",
    kategori: "toner/moisturizer",
    jerawat: "Papular",
    jenisSkincare: "Toner/Moisturizer",
    rekomendasi: "Memperkuat skin barrier dan menenangkan kulit yang teriritasi, ideal untuk kulit sensitif.",
    gambar: "images/produk/toner-a.png",
    kandungan: "Ceramide NP, Centella Asiatica, Panthenol",
    keterangan: "Memperkuat skin barrier dan menenangkan kulit yang teriritasi, ideal untuk kulit sensitif.",
    link: "https://s.shopee.co.id/COSRX-Balancium-Comfort-Moisturizing-Ceramide-Cream-80-gr-i.4911147.2242290409?sp_atk=76b84f88-d187-4360-bf34-f344eec7a61c&xptdk=76b84f88-d187-4360-bf34-f344eec7a61c",
  },
  {
    nama: "The Ordinary Niacinamide 10% + Zinc 1%",
    kategori: "serum/salep",
    jerawat: "Papular",
    jenisSkincare: "Serum/Salep",
    rekomendasi: "Mengontrol produksi sebum, mencerahkan kulit, dan meredakan jerawat ringan.",
    gambar: "images/produk/serum-a.jpg",
    kandungan: "Niacinamide, Zinc PCA",
    keterangan: "Mengontrol produksi sebum, mencerahkan kulit, dan meredakan jerawat ringan.",
    link: "https://s.shopee.co.id/The-Ordinary-Niacinamide-10-Zinc-1--i.786684232.25476314700?sp_atk=98b6ae56-e31a-4628-8641-40e7cc6a425f&xptdk=98b6ae56-e31a-4628-8641-40e7cc6a425f",
  },
  {
    nama: "Some By Mi AHA BHA PHA 30 Days Miracle Acne Clear Foam",
    kategori: "cleanser",
    jerawat: "Purulent",
    jenisSkincare: "Cleanser",
    rekomendasi: "Membersihkan pori dan membantu eksfoliasi ringan sambil menenangkan kulit berjerawat.",
    gambar: "images/produk/cleanser-f.jpg",
    kandungan: "AHA, BHA, PHA, Centella Asiatica",
    keterangan: "Membersihkan pori dan membantu eksfoliasi ringan sambil menenangkan kulit berjerawat.",
    link: "https://shopee.co.id/SOME-BY-MI-AHA-BHA-PHA-30-Days-Miracle-Acne-Clear-Foam-100ml-Membersihkan-kulit-jerawat-membersihkan-Pori-pori-(Sabun-Cuci-Wajah-Untuk-Jerawat-Komedo)-i.1517125587.27634234809?sp_atk=044a5194-ebf0-479d-a867-f0522a3d1034&xptdk=044a5194-ebf0-479d-a867-f0522a3d1034",
  },
  {
    nama: "Centella Asiatica Cream – Skin1004 Madagascar Soothing Cream",
    kategori: "toner/moisturizer",
    jerawat: "Purulent",
    jenisSkincare: "Toner/Moisturizer",
    rekomendasi: "Menenangkan peradangan dan mempercepat penyembuhan kulit tanpa rasa berat.",
    gambar: "images/produk/toner-e.jpg",
    kandungan: "72% Centella Asiatica Extract",
    keterangan: "Menenangkan peradangan dan mempercepat penyembuhan kulit tanpa rasa berat.",
    link: "https://shopee.co.id/SKIN1004-Madagascar-Centella-Soothing-Cream-75ml-30ml-i.629000745.15885471858?sp_atk=35390482-d8b6-4dba-896f-6d0baef167ed&xptdk=35390482-d8b6-4dba-896f-6d0baef167ed",
  },
  {
    nama: "COSRX Centella Blemish Cream",
    kategori: "serum/salep",
    jerawat: "Purulent",
    jenisSkincare: "Serum/Salep",
    rekomendasi: "Mengatasi jerawat aktif dan membantu memperbaiki bekas jerawat dengan efek menenangkan.",
    gambar: "images/produk/serum-f.png",
    kandungan: "Zinc Oxide, Centella Asiatica Leaf Water",
    keterangan: "Mengatasi jerawat aktif dan membantu memperbaiki bekas jerawat dengan efek menenangkan.",
    link: "https://shopee.co.id/Cosrx-Centella-Blemish-Cream-30-ml-Krim-Totol-Jerawat-Skincare-i.224957239.7029834077?sp_atk=bfbeb632-ab0e-4ffb-b27e-73e1246cbe2d&xptdk=bfbeb632-ab0e-4ffb-b27e-73e1246cbe2d",
  },
  {
    nama: "Krave Beauty Matcha Hemp Hydrating Cleanser",
    kategori: "cleanser",
    jerawat: "Scars",
    jenisSkincare: "Cleanser",
    rekomendasi: "Membersihkan dengan lembut sekaligus memberikan antioksidan dan kelembapan untuk kulit.",
    gambar: "images/produk/cleanser-c.jpg",
    kandungan: "Matcha (Camellia Sinensis), Hemp Seed Oil, Vitamin B5",
    keterangan: "Membersihkan dengan lembut sekaligus memberikan antioksidan dan kelembapan untuk kulit.",
    link: "https://shopee.co.id/KRAVE-Matcha-Hemp-Hydrating-Cleanser-i.1286003.1701666683?sp_atk=c2ba9757-375a-49a0-acab-dee4ffde1e37&xptdk=c2ba9757-375a-49a0-acab-dee4ffde1e37",
  },
  {
    nama: "Some By Mi Snail Truecica Miracle Repair Toner",
    kategori: "toner/moisturizer",
    jerawat: "Scars",
    jenisSkincare: "Toner/Moisturizer",
    rekomendasi: "Memperbaiki bekas jerawat dan memperkuat barrier kulit secara perlahan.",
    gambar: "images/produk/toner-f.jpg",
    kandungan: "Black Snail Mucin, Truecica™, Niacinamide",
    keterangan: "Memperbaiki bekas jerawat dan memperkuat barrier kulit secara perlahan.",
    link: "https://s.shopee.co.id/SOMEBYMI-Snail-Truecica-Miracle-Repair-Toner-150ml-30ml-i.629000745.17322409665?sp_atk=eaf624c7-940a-4c84-bf4e-f0206bb2ff85&xptdk=eaf624c7-940a-4c84-bf4e-f0206bb2ff85",
  },
  {
    nama: "Goodal Green Tangerine Vita C Serum",
    kategori: "serum/salep",
    jerawat: "Scars",
    jenisSkincare: "Serum/Salep",
    rekomendasi: "Mencerahkan kulit dan menyamarkan dark spots/bekas jerawat secara bertahap tanpa iritasi.",
    gambar: "images/produk/serum-c.jpg",
    kandungan: "70% Green Tangerine Extract (natural Vitamin C), Niacinamide",
    keterangan: "Mencerahkan kulit dan menyamarkan dark spots/bekas jerawat secara bertahap tanpa iritasi.",
    link: "https://shopee.co.id/GOODAL-Green-Tangerine-Vita-C-Dark-Spot-Care-Serum-Sheet-Mask-5x28g-i.1521300491.40450725987?sp_atk=70879c4e-037c-47ce-9510-b0c3ea04a698&xptdk=70879c4e-037c-47ce-9510-b0c3ea04a698",
  },
  {
    nama: "COSRX Low pH Good Morning Cleanser",
    kategori: "cleanser",
    jerawat: "Whitehead",
    jenisSkincare: "Cleanser",
    rekomendasi: "Menjaga keseimbangan pH kulit sambil membersihkan pori-pori dengan lembut, ideal untuk pagi hari.",
    gambar: "images/produk/cleanser-k.png",
    kandungan: "Tea Tree Oil, Betaine Salicylate",
    keterangan: "Menjaga keseimbangan pH kulit sambil membersihkan pori-pori dengan lembut, ideal untuk pagi hari.",
    link: "https://s.shopee.co.id/COSRX-Mengangkat-Sel-Sel-Kulit-Mati-Dan-Minyak-Berlebih-Low-pH-Good-Morning-Cleanser-50-ML-(Sabun-Wajah-Untuk-Semua-Jenis-Kulit)-Best-Seller-i.404429429.5389408407?sp_atk=58c4a710-c8ee-45e0-83b0-b75c25338a22&xptdk=58c4a710-c8ee-45e0-83b0-b75c25338a22",
  },
  {
    nama: "The Inkey List PHA Toner",
    kategori: "toner/moisturizer",
    jerawat: "Whitehead",
    jenisSkincare: "Toner/Moisturizer",
    rekomendasi: "Eksfoliasi ringan untuk kulit sensitif tanpa mengiritasi, membantu memperbaiki tekstur kulit.",
    gambar: "images/produk/toner-c.jpg",
    kandungan: "Polyhydroxy Acid (PHA), Aloe Vera",
    keterangan: "Eksfoliasi ringan untuk kulit sensitif tanpa mengiritasi, membantu memperbaiki tekstur kulit.",
    link: "https://shopee.co.id/THE-INKEY-LIST-PHA-toner-%28-100ml-%29-i.16306254.4551686108",
  },
  {
    nama: "Paula's Choice 2% BHA Liquid Exfoliant",
    kategori: "serum/salep",
    jerawat: "Whitehead",
    jenisSkincare: "Serum/Salep",
    rekomendasi: "Membersihkan pori-pori tersumbat, mengurangi jerawat, dan menghaluskan tekstur kulit.",
    gambar: "images/produk/serum-d.jpg",
    kandungan: "Salicylic Acid (BHA)",
    keterangan: "Membersihkan pori-pori tersumbat, mengurangi jerawat, dan menghaluskan tekstur kulit.",
    link: "https://shopee.co.id/Paula's-Choice-Skin-Perfecting-2-BHA-Liquid-Exfoliant-30ml-Liquid-Exfoliant-118ml-%EF%BC%88Meratakan-dan-mencerahkan-warna-kulit%EF%BC%89-Dalam-stok-i.1206997887.25070309748?sp_atk=c74e42d-6419-463b-b1cd-5e6c297ad8a1&xptdk=c74e42d-6419-463b-b1cd-5e6c297ad8a1",
  },
];

export default skincareProducts;